from routes.character.assets import *
from routes.character.bookmarks import *
from routes.character.calendar import *
from routes.character.clones import *
from routes.character.contacts import *
from routes.character.finance import *
from routes.character.fittings import *
from routes.character.mail import *
from routes.character.mining import *
from routes.character.planetary_interaction import *
from routes.character.skills import *
from routes.character.industry import *
from routes.character.blueprints import *
