from routes.character import *
from routes.corporation import *
from routes.application import *
from routes.login import *
from routes.mail import *
from routes.maintenance import *
from routes.notes import *
from routes.questions import *
from routes.search import *
from routes.users import *
from routes.list import *
from routes.roles import *
