runtime: python37
#api_version: 1
#threadsafe: true

#libraries:
#- name: ssl
#  version: latest

handlers:
- url: /app
  static_dir: public
- url: /static
  static_dir: public/static
- url: /.*
  script: main.app
