"""empty message

Revision ID: a45be72e861d
Revises: b20b0fabc158
Create Date: 2019-03-29 11:27:50.835065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45be72e861d'
down_revision = 'b20b0fabc158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporation', sa.Column('ceo_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporation', 'ceo_id')
    # ### end Alembic commands ###
