"""empty message

Revision ID: b20b0fabc158
Revises: 
Create Date: 2019-03-24 15:43:35.639871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20b0fabc158'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'is_escalated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('is_escalated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
